esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${comment}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 0min
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"
    password: !secret wifi_password

api:
  encryption:
    key: !secret apiKey

ota:
  - platform: esphome
    password: !secret otaPassword

logger:
  level: DEBUG